### ISSUE TITLE
Tracer update

### ISSUE THREAD

**Issue by Talha-Ahmed-1** [merledu/tracer#1]
@5hayanB put your chisel based tracer here.

**Comment by 5hayanB** [comment]
@Talha-Ahmed-1, do I make a CHISEL project or just put a scala file in here?

**Comment by Talha-Ahmed-1** [comment]
Create a chisel project, in future it will be used as submodule.

**Comment by Talha-Ahmed-1** [comment]
Simply place build.sbt and run sbt here.

**Comment by 5hayanB** [comment]
I've added the tracer
